const KEY = 'smartec-pwa-draft-v1';
const API = './api/index.php?resource=';
const empty = () => ({ clients: [], services: [], finances: [], tools: [], orders: [], sequence: 0 });
function read() { try { return { ...empty(), ...(JSON.parse(localStorage.getItem(KEY)) || {}) }; } catch { return empty(); } }
function write(data) { localStorage.setItem(KEY, JSON.stringify(data)); }
function localId() { return crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`; }
const state = { data: read(), mode: 'offline', initialized: false, loading: null, user: null, loginRequired: false, csrf: '' };
async function request(resource, options = {}) { const method = options.method || 'GET'; const response = await fetch(`${API}${resource}`, { credentials: 'same-origin', headers: { ...(options.body ? { 'Content-Type': 'application/json' } : {}), ...(method !== 'GET' && state.csrf ? { 'X-CSRF-Token': state.csrf } : {}), ...(options.headers || {}) }, ...options }); const payload = await response.json().catch(() => ({})); if (!response.ok) { const error = new Error(payload.error || 'Não foi possível comunicar com o servidor.'); error.status = response.status; throw error; } return payload; }
function mapRemote(data) { return { clients: data.clients.map((item) => ({ ...item, id: String(item.id) })), services: data.services.map((item) => ({ id: String(item.id), name: item.name, description: item.description || '', price: item.reference_price, createdAt: item.created_at })), finances: data.finances.map((item) => ({ id: String(item.id), description: item.description, amount: item.amount, dueDate: item.due_date, status: item.status, createdAt: item.created_at })), tools: data.tools.map((item) => ({ id: String(item.id), name: item.name, code: item.asset_code || '', status: item.status, notes: item.notes || '', createdAt: item.created_at })), orders: data.orders.map((item) => ({ id: String(item.id), number: Number(item.number), clientId: String(item.client_id), type: item.type, status: item.status, date: item.service_date, description: item.description, notes: item.notes || '', amount: item.amount, photo: item.photo_path || '', createdAt: item.created_at, updatedAt: item.updated_at })), sequence: Math.max(0, ...data.orders.map((item) => Number(item.number) || 0)) }; }
async function refreshRemote() { const [clients, services, finances, tools, orders] = await Promise.all([request('clients'), request('services'), request('financial-entries'), request('tools'), request('orders')]); state.data = mapRemote({ clients, services, finances, tools, orders }); }
async function ensure() { if (state.initialized) return; if (state.loading) return state.loading; state.loading = (async () => { try { const auth = await request('auth/me'); state.user = auth.user; state.csrf = auth.csrf || ''; await refreshRemote(); state.mode = 'online'; state.loginRequired = false; } catch (error) { state.user = null; state.csrf = ''; state.data = read(); state.mode = 'offline'; state.loginRequired = error.status === 401; } finally { state.initialized = true; state.loading = null; } })(); return state.loading; }
function persistLocal(change) { const data = read(); change(data); state.data = data; write(data); }
async function remoteChange(resource, method, values, id = '') { await request(`${resource}${id ? `&id=${encodeURIComponent(id)}` : ''}`, { method, body: values ? JSON.stringify(values) : undefined }); await refreshRemote(); }
export const store = {
  initialize: ensure, mode: () => state.mode, user: () => state.user, needsLogin: () => state.loginRequired,
  async login(email, password) { const auth = await request('auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }); state.csrf = auth.csrf || ''; state.initialized = false; await ensure(); },
  async logout() { await request('auth/logout', { method: 'POST' }); state.initialized = false; state.user = null; state.csrf = ''; state.loginRequired = true; },
  clients: () => [...state.data.clients].sort((a, b) => a.name.localeCompare(b.name, 'pt-BR')), services: () => [...state.data.services].sort((a, b) => a.name.localeCompare(b.name, 'pt-BR')), finances: () => [...state.data.finances].sort((a, b) => a.dueDate.localeCompare(b.dueDate)), tools: () => [...state.data.tools].sort((a, b) => a.name.localeCompare(b.name, 'pt-BR')), orders: () => [...state.data.orders].sort((a, b) => String(b.createdAt).localeCompare(String(a.createdAt))),
  clientName: (id) => state.data.clients.find((item) => String(item.id) === String(id))?.name || 'Cliente removido', hasOrders: (id) => state.data.orders.some((item) => String(item.clientId) === String(id)), order: (id) => state.data.orders.find((item) => String(item.id) === String(id)),
  async addClient(f) { if (state.mode === 'online') return remoteChange('clients', 'POST', { name: f.name, document: f.document || '', phone: f.phone || '', email: f.email || '', address: f.address || '' }); persistLocal((d) => d.clients.push({ id: localId(), ...f, createdAt: new Date().toISOString() })); },
  async addService(f) { if (state.mode === 'online') return remoteChange('services', 'POST', { name: f.name, description: f.description || '', reference_price: f.price || 0 }); persistLocal((d) => d.services.push({ id: localId(), ...f, createdAt: new Date().toISOString() })); },
  async deleteService(id) { if (state.mode === 'online') return remoteChange('services', 'DELETE', null, id); persistLocal((d) => d.services = d.services.filter((x) => x.id !== id)); },
  async addFinance(f) { if (state.mode === 'online') return remoteChange('financial-entries', 'POST', { description: f.description, amount: f.amount, due_date: f.dueDate, status: f.status }); persistLocal((d) => d.finances.push({ id: localId(), ...f, createdAt: new Date().toISOString() })); },
  async deleteFinance(id) { if (state.mode === 'online') return remoteChange('financial-entries', 'DELETE', null, id); persistLocal((d) => d.finances = d.finances.filter((x) => x.id !== id)); },
  async addTool(f) { if (state.mode === 'online') return remoteChange('tools', 'POST', { name: f.name, asset_code: f.code || '', status: f.status, notes: f.notes || '' }); persistLocal((d) => d.tools.push({ id: localId(), ...f, createdAt: new Date().toISOString() })); },
  async deleteTool(id) { if (state.mode === 'online') return remoteChange('tools', 'DELETE', null, id); persistLocal((d) => d.tools = d.tools.filter((x) => x.id !== id)); },
  async deleteClient(id) { if (state.mode === 'online') return remoteChange('clients', 'DELETE', null, id); persistLocal((d) => d.clients = d.clients.filter((x) => x.id !== id)); },
  async addOrder(f) { if (state.mode === 'online') return remoteChange('orders', 'POST', { client_id: f.clientId, type: f.type, status: f.status, service_date: f.date, description: f.description, notes: f.notes || '', amount: f.amount || 0, photo_path: '' }); persistLocal((d) => { d.sequence += 1; d.orders.push({ id: localId(), number: d.sequence, ...f, createdAt: new Date().toISOString() }); }); },
  async updateOrder(id, f) { if (state.mode === 'online') return remoteChange('orders', 'PATCH', { client_id: f.clientId, type: f.type, status: f.status, service_date: f.date, description: f.description, notes: f.notes || '', amount: f.amount || 0 }, id); persistLocal((d) => d.orders = d.orders.map((x) => x.id === id ? { ...x, ...f, updatedAt: new Date().toISOString() } : x)); },
  async deleteOrder(id) { if (state.mode === 'online') return remoteChange('orders', 'DELETE', null, id); persistLocal((d) => d.orders = d.orders.filter((x) => x.id !== id)); },
  async users() { if (state.mode !== 'online') return []; return request('users'); },
  async addUser(fields) { return request('users', { method: 'POST', body: JSON.stringify(fields) }); },
  async deleteUser(id) { return request(`users&id=${encodeURIComponent(id)}`, { method: 'DELETE' }); },
};
